lst=list(range(1,51,1))
print('The list is...')
print(lst)
squares=list(map(lambda x: x*x,lst))
print('_'*90)
print('using map function squares list each element')
print(squares)
print('_'*90)
print('Using filter function return even numbers')
even=list(filter(lambda x:x%2==0,lst))
print(even)
print('_'*90)
print('Using filter function return odd numbers')
odd=list(filter(lambda x:x%2!=0,lst))
print(odd)
